# Generated by Django 5.2.7 on 2026-03-14 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chapa_tx_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(default='Construction License Payment', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=uuid.uuid4, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
