# Generated by Django 5.2.7 on 2026-03-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_chapa_tx_id_payment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
