# Generated by Django 5.2.7 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
