# Generated by Django 5.2.7 on 2026-03-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('applicant', 'Applicant')], default='applicant', max_length=20),
        ),
    ]
