# Generated by Django 5.2.7 on 2026-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
