# Generated by Django 6.0.2 on 2026-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreply',
            name='send_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='send_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='contactreply',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
