# Generated by Django 6.0.2 on 2026-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0003_systemsettings_document_verification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_ip_whitelist',
            field=models.TextField(blank=True, default=''),
        ),
    ]
