# Generated by Django 6.0.2 on 2026-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0004_systemsettings_admin_ip_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_refresh_token',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
