# Generated by Django 6.0.2 on 2026-03-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0005_systemsettings_gmail_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='use_gmail_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
