# Generated by Django 5.2.7 on 2026-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0007_systemsettings_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, default='', help_text='Groq API key for Llama 3 Vision document verification', max_length=255),
        ),
    ]
