# Generated by Django 5.2.7 on 2026-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0008_systemsettings_groq_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='grok_api_key',
            field=models.CharField(blank=True, default='', help_text='xAI Grok API key for document verification', max_length=255),
        ),
    ]
