# Generated by Django 5.2.7 on 2026-03-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0009_systemsettings_grok_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='grok_api_key',
        ),
    ]
