# Generated by Django 5.2.7 on 2026-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0010_remove_systemsettings_grok_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq')], default='groq', help_text='Primary AI provider to use for document verification', max_length=20),
        ),
    ]
