# Generated by Django 5.2.7 on 2026-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0011_systemsettings_preferred_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='chapa_base_url',
            field=models.CharField(default='https://api.chapa.co/v1', help_text='Chapa API Base URL', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chapa_secret_key',
            field=models.CharField(blank=True, default='', help_text='Chapa Secret Key (starts with CHASECK_)', max_length=255),
        ),
    ]
