# Generated by Django 5.2.7 on 2026-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0012_systemsettings_chapa_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='chapa_base_url',
            field=models.URLField(default='https://api.chapa.co/v1', help_text='Chapa API base URL'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='chapa_secret_key',
            field=models.CharField(blank=True, default='', help_text='Chapa API secret key', max_length=255),
        ),
    ]
