# Generated by Django 5.2.7 on 2026-03-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0013_alter_systemsettings_chapa_base_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_client_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_client_secret',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_refresh_token',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_gmail_oauth',
        ),
    ]
