# Generated by Django 5.2.7 on 2026-03-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0014_remove_systemsettings_gmail_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='preferred_ai_provider',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, default='', help_text='DeepSeek API key for document verification', max_length=255),
        ),
    ]
