# Generated by Django 5.2.7 on 2026-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0015_remove_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Gemini API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='groq_api_key',
            field=models.CharField(blank=True, default='', help_text='Groq API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('groq', 'Groq')], default='gemini', max_length=20),
        ),
    ]
