# Generated by Django 5.2.7 on 2026-03-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0016_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='preferred_ai_provider',
        ),
    ]
