# Generated by Django 5.2.7 on 2026-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0017_remove_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_document_types',
            field=models.TextField(default='pdf,jpg,jpeg,png,gif'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chapa_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retries for failed DeepSeek API calls'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_model',
            field=models.CharField(default='deepseek-chat', help_text='DeepSeek model to use: deepseek-chat or deepseek-reasoner', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for DeepSeek API calls'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_document_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_document_resolution',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_language',
            field=models.CharField(default='amh+eng', help_text="Tesseract OCR language packs (e.g., 'amh+eng' for Amharic+English)", max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_timeout',
            field=models.IntegerField(default=30, help_text='Timeout in seconds for OCR processing'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
