# Generated by Django 5.2.7 on 2026-03-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0018_alter_systemsettings_options_and_more'),
    ]

    operations = [
    ]
