# Generated by Django 5.2.7 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0019_manual_field_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_ip_whitelist',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_document_types',
            field=models.TextField(default='pdf,jpg,jpeg,png,gif'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, default='', help_text='DeepSeek API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_max_retries',
            field=models.IntegerField(default=3, help_text='Maximum number of retries for failed DeepSeek API calls'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_model',
            field=models.CharField(default='deepseek-chat', help_text='DeepSeek model to use: deepseek-chat or deepseek-reasoner', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='deepseek_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for DeepSeek API calls'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_document_size_mb',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='min_document_resolution',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_language',
            field=models.CharField(default='amh+eng', help_text="Tesseract OCR language packs (e.g., 'amh+eng' for Amharic+English)", max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ocr_timeout',
            field=models.IntegerField(default=30, help_text='Timeout in seconds for OCR processing'),
        ),
    ]
