# Generated by Django 5.2.7 on 2026-03-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0020_manual_field_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenAI API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_model',
            field=models.CharField(default='gpt-4o', help_text='OpenAI model to use (e.g., gpt-4o, gpt-4-turbo, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openai_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for OpenAI API calls'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI')], default='deepseek', help_text='Switch between DeepSeek and OpenAI for document verification', max_length=20),
        ),
    ]
