# Generated by Django 5.2.7 on 2026-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0021_systemsettings_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Gemini API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Gemini model to use (e.g., gemini-2.0-flash, gemini-1.5-pro, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gemini_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for Gemini API calls'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], default='deepseek', help_text='Switch between DeepSeek, OpenAI and Gemini for document verification', max_length=20),
        ),
    ]
