# Generated by Django 5.2.7 on 2026-03-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0022_systemsettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_client_id',
            field=models.CharField(blank=True, default='', help_text='Google OAuth2 Client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_client_secret',
            field=models.CharField(blank=True, default='', help_text='Google OAuth2 Client Secret', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, default='', help_text='Google OAuth2 Refresh Token'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_gmail_oauth',
            field=models.BooleanField(default=False, help_text='Use Gmail OAuth2 instead of standard SMTP'),
        ),
    ]
