# Generated by Django 5.2.7 on 2026-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0023_systemsettings_gmail_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='smtp_user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_tls',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='use_gmail_oauth',
            field=models.BooleanField(default=False, help_text='Use Gmail OAuth2 for document verification'),
        ),
    ]
