# Generated by Django 5.2.7 on 2026-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0024_remove_systemsettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_debug_mode',
            field=models.BooleanField(default=False, help_text='If enabled, emails will be printed to the console instead of being sent.'),
        ),
    ]
