# Generated by Django 5.2.7 on 2026-03-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0025_systemsettings_email_debug_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_client_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_client_secret',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='gmail_refresh_token',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_gmail_oauth',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, default='', help_text='Brevo API Key', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='use_brevo',
            field=models.BooleanField(default=False, help_text='Use Brevo API for email delivery'),
        ),
    ]
