# Generated by Django 5.2.7 on 2026-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0026_remove_systemsettings_gmail_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='use_brevo',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_provider',
            field=models.CharField(choices=[('brevo', 'Brevo'), ('smtp', 'SMTP')], default='brevo', help_text='Email service provider', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text='Brevo API Key', max_length=255),
        ),
    ]
