# Generated by Django 5.2.7 on 2026-03-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0028_add_smtp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='brevo_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='email_provider',
        ),
    ]
