# Generated by Django 5.2.7 on 2026-03-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0029_remove_systemsettings_brevo_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_timeout',
            field=models.IntegerField(default=10, help_text='Timeout in seconds for SMTP connection.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
