# Generated by Django 5.2.7 on 2026-03-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0030_systemsettings_smtp_timeout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='openai_model',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='openai_timeout',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenRouter API key for document verification', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openrouter_model',
            field=models.CharField(default='google/gemini-2.0-flash-001', help_text='OpenRouter model to use (e.g., google/gemini-2.0-flash-001, meta-llama/llama-3-70b-instruct, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='openrouter_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for OpenRouter API calls'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter')], default='deepseek', help_text='Switch between DeepSeek, OpenAI, Gemini and OpenRouter for document verification', max_length=20),
        ),
    ]
