# Generated by Django 5.2.7 on 2026-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0031_remove_systemsettings_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='preferred_ai_provider',
            field=models.CharField(choices=[('deepseek', 'DeepSeek'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter')], default='deepseek', help_text='Switch between DeepSeek, Gemini and OpenRouter for document verification', max_length=20),
        ),
    ]
