# Generated by Django 5.2.7 on 2026-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0032_alter_systemsettings_preferred_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='notification_template',
            field=models.TextField(default='Dear {name}, \n \n Your application id  {id} has been {status}. \n \n Thank you for using CLMS.'),
        ),
    ]
