# Generated by Django 5.2.7 on 2026-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0033_alter_systemsettings_notification_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ip_whitelist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='two_factor_authentication_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
