# Generated by Django 5.2.7 on 2026-03-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='unique_vehicle_per_owner',
        ),
    ]
