# Generated by Django 5.2.7 on 2026-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehicle_unique_vehicle_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
