# Generated by Django 5.2.7 on 2026-03-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='download_count',
        ),
    ]
