# Generated by Django 5.2.7 on 2026-02-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0007_remove_partnership_cp_id'),
        ('partnerships', '0007_unique_partnership_owner'),
    ]

    operations = [
    ]
