# Generated by Django 5.2.7 on 2026-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0008_merge_20260227_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipdocument',
            name='verification_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnershipdocument',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershipdocument',
            name='verification_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='partnershipdocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
