# Generated by Django 5.2.7 on 2026-03-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0009_partnershipdocument_verification_details_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partnership',
            name='unique_partnership_per_owner',
        ),
    ]
