# Generated by Django 5.2.7 on 2026-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0010_remove_partnership_unique_partnership_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
