# Generated by Django 5.2.7 on 2026-02-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('licenses', '0009_license_previous_license_alter_license_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_licenses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='license',
            name='replacement_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='replaces_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_licenses', to='licenses.license'),
        ),
    ]
