# Generated by Django 5.2.7 on 2026-03-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0010_license_company_license_replacement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
